import React from 'react';
import './About.css'
export const About = () => {
  return (<div className='container '>
    <div className="row about text-center mt-5">About Page</div>
    <div className="row mb-5 pb-5 mt-4">
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur similique ratione neque? Aspernatur consectetur, consequuntur amet similique, earum numquam molestiae maxime ex, quisquam nisi quas sint eum beatae aperiam libero in quo temporibus doloremque fugiat obcaecati id officia est repudiandae assumenda. Tempora quibusdam ducimus nisi minima optio officiis ipsum provident quasi reprehenderit iure ea est at debitis temporibus enim, numquam voluptatum animi neque laudantium nemo? Velit voluptatem, expedita esse itaque ad quisquam atque voluptatum eum architecto officiis voluptate debitis corrupti iusto, odio nulla eos cumque ipsa, distinctio veniam vitae. Quae provident sequi culpa in officiis repellat perferendis itaque at impedit voluptas debitis delectus, velit dolorem error molestias deserunt laudantium nobis ex iure! Et tempora expedita fugit commodi. Tempora, beatae sed. Atque, iusto similique eum reprehenderit pariatur aliquid impedit amet vitae animi officia facere modi? Maxime nisi nobis, esse excepturi labore atque eum inventore repellat libero autem dolorum nam tenetur rerum at delectus dolore sequi facere. Tenetur omnis, consequatur nostrum aut rem impedit assumenda deleniti voluptas ad? Porro, corporis eos. Modi natus, maxime consectetur accusamus ab illo iste quis dolor praesentium ex magni veritatis incidunt, ea enim nesciunt debitis consequuntur dicta necessitatibus vero iusto porro laboriosam atque! Perspiciatis deleniti eligendi natus dolorum laboriosam animi commodi veritatis cupiditate, ipsam, soluta quidem esse ipsa tempora praesentium rerum ea incidunt corrupti? Cumque, illo, facilis saepe odit deleniti quis aperiam pariatur quia amet tempora quod. Sit unde error aspernatur a. Iste laudantium est in eveniet. Accusamus, ipsa enim! Dolorum placeat modi sequi officia, rem voluptas, corporis eos laboriosam sint dicta corrupti labore, omnis inventore a ipsam quam sed officiis voluptatum perferendis! Magnam incidunt laborum beatae quia blanditiis id quas soluta aliquid consectetur unde accusantium vero quod repudiandae excepturi, doloribus adipisci omnis! Tempore unde et soluta, eum nihil earum illum reiciendis. Ipsum necessitatibus quia odit expedita?
    </div>
  </div>);
};
